[[ constraint ]]
  name = "github.com/containerd/containerd"
  revision = "773c489c9c1b21a6d78b5c538cd395416ec50f88"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"
